### ISSUE TITLE
Multiple top-level headings in the same document

### ISSUE THREAD

**Issue by VunkLai** [LeoTunero/first_side_project#1]
A top level header should be a h1, on the first line of the file, and there should be no other h1 headers in the file.

You neek a Markdown linting and style checking for VSCode.
Try this, [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)

**Comment by LeoTunero** [comment]
ok
I have revised the README.md and fixed the mult-H1 issue
please check the README.md

**Comment by VunkLai** [comment]
Fixed  LeoTunero@ab095b895d05406d7c50c60d33a43da417b60467
