### ISSUE TITLE
why the template is not working?

### ISSUE THREAD

**Issue by LeoTunero** [LeoTunero/first_side_project#12]
I have commit the code.
I have tried many times but I still cannot understand this page.
![image](https://user-images.githubusercontent.com/85209003/127744435-9e726e15-6676-415e-96df-9580afcf6368.png)
why the message say so?
why it cannot get it template correctly?
LeoTunero @ <271d0cd >

**Comment by LeoTunero** [comment]
I have fixed this problem already.

**Comment by VunkLai** [comment]
## FYR 
Search `How Django Finds Templates` and `Creating a Site Template` in [Template](https://djangobook.com/mdj2-django-templates/)

## The is a invalid syntax.
```
LeoTunero @ <271d0cd >
```
You should click `Preview` before submit a comment

**Comment by LeoTunero** [comment]
the template is working!!
Leotunero @ [32b1134]
So this is what you want for the basic ??

**Comment by VunkLai** [comment]
### First: the template is working!!

I understand. But, would you read the article.
The two sections are about `How Django **Finds** Templates` and `Creating a **Site** Template`.

For example, in article.
> When you tell Django to load the template index.html it will load the first file it finds (based on the order of your apps in the INSTALLED_APPS setting)

But you have two template dirs, `DIRS` and `APP_DIRS`. So, which one goes first?
```python
TEMPLATES = [
     {
         'BACKEND': 'django.template.backends.django.DjangoTemplates',
          'DIRS': [os.path.join(BASE_DIR, 'myclub_site/templates')],
          'APP_DIRS': True,
         # ...
```

### Second: So this is what you want for the basic ??

yes, A link is better than the string.
Next, keep it simple. 

Do you read the reference in #5 ?
Always I use " Leotunero@32b1134 " rather than " Leotunero @ [32b1134] "

**Comment by VunkLai** [comment]
Hey, does your commit refs are correct?

The ref, 271d0cd, is ok for me.
This commit has a problem that raise `TemplateDoesNotExist`

But, you fix this issue in 4dfe575e , not 32b1134.
Could you explain me way you tag 32b1134 for me?

**Comment by LeoTunero** [comment]
Could you explain me way you tag 32b1134 for me?
I did this because I have updated the details.
Even though I have fixed the issue in 4dfe575, but I thought any version after 4dfe575 is fine.
Therefore, I have tag the 32b1134 for your ref.

**Comment by VunkLai** [comment]
> 幹我們這行，用詞要精準，講話要準確... _(相聲瓦舍：迷香)_

A commit ref points to a specific commit details page that to help people understand your changes or ideas.
Referencing a correct commit in an issue comment is very important.

**Comment by LeoTunero** [comment]
understood
I am trying to pill these acknowledge up
I thought I have read too much and coding too less
I have seen a lot of tests & git pro kind of information
I am still organizing all of them together to improve my program

**Comment by LeoTunero** [comment]
I am going to adjust my vocabulary
I will use it as exact as possible like you taught to me
