### ISSUE TITLE
Remove committed db.sqlite3 from your repo. and add .gitignore file

### ISSUE THREAD

**Issue by VunkLai** [LeoTunero/first_side_project#3]
FYR.
[Remove commited file](https://mtr04-note.coderbridge.io/2020/08/09/about-git-deletefile/)
[Add .gitignore](https://gitbook.tw/chapters/using-git/ignore.html)

**Comment by LeoTunero** [comment]
done
I have commit the .gitignore to the branch 'side_project'

**Comment by VunkLai** [comment]
[Remove commited file](https://mtr04-note.coderbridge.io/2020/08/09/about-git-deletefile/)

**Comment by LeoTunero** [comment]
I have revise the .gitignore & delete the db file on GitHub
I have also removed all the commit's trace by the filter-branch

LeoTunero@<113e5a5>
