### ISSUE TITLE
Your commits have two users

### ISSUE THREAD

**Issue by VunkLai** [LeoTunero/first_side_project#4]
FYR. [Why are my commits linked to the wrong user?](https://docs.github.com/en/github/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user)

**Comment by LeoTunero** [comment]
i will use LeoTunero all the time from now on because there are so many Leo out there
I will learn how to manage all the different password as well
So do I need to delete the Leo ?
or I could just ignore it

**Comment by VunkLai** [comment]
Let's discuss it later. friday night?

**Comment by LeoTunero** [comment]
ya~ sure!!
see you on Fri.
