### ISSUE TITLE
what the hell is migration?

### ISSUE THREAD

**Issue by LeoTunero** [LeoTunero/first_side_project#6]
I have successfully start the Django on my browser.
when I move on to the next step, something is different between my terminal and the example on the page.
![image](https://user-images.githubusercontent.com/85209003/126497864-e33230c2-dd98-4331-8e6e-2e48f85d8320.png)
somehow they get the migration to apply and I have none of them. 
therefore, I cannot build the login-in function on my Django after the setting of user name & password.
So my question is what is migration?
Why I didn't have any of them?
Should I build some of them?
Or it gets nothing to do with the login-in function?

**Comment by VunkLai** [comment]
First, you should push your codes, and than, you can tag the commit ref in here.

-- Mediumshop --
You are building an authentication system.

1. If you want to use the User model (built-in model in Django)
   - The User model is migrated on you first run `migrate`
2. If you want to make your dedicated model
   - Your could append your app name to INSTALLED_APPS, and create a model that is inheriting from `django.db.models.Model` class
   - Finally, run `migrate` to create the table on database

**Comment by LeoTunero** [comment]
well
I have couple of questions here.
First of all, you said that I should push my code here.
However, as you can see, I only type some command on my terminal.
I could edit the code, setting.py for example, in the VScode.
Than I know how to push them up to GitHub.
But those command which I have key in the terminal I have no idea how to push them to GitHub.

More importantly, for this paragraph 'The User model is migrated on you first run migrate'
I have done that and the program had replied me that 'No migrations to apply'
So maybe I should build a DB first in order to storage the user name & password?
db.sqlite3 → is this the file I should revise?
but when I was trying to do so, I have seen this message
![image](https://user-images.githubusercontent.com/85209003/126647036-ac6c4eae-2da3-4823-a267-88bc959aa561.png)
I have no idea where should I build in my own DB.

**Comment by VunkLai** [comment]
Django allows you to directly map your object-oriented models to a database.
But, how does it work?

1. A model was registered. (INSTALLED_APPS and inherit from Django Model)
2. Executing `makemigrations` command will create **a migration**
3. When you have a migration that does not migrate yet and you execute `migrate` command, the migration will have applied.

In other words, 
`migration` is a mapping between the model and the table of database. 
`makemigration` creates a migration file for a registered model.
`migrate` is an action that create/update a table using migrations

**Comment by LeoTunero** [comment]
I am going to close this issue for now.
Wait to deal with it until next time
