### ISSUE TITLE
the Post function did not work as I exepcted

### ISSUE THREAD

**Issue by LeoTunero** [LeoTunero/first_side_project#7]
LeoTunero@<71d82e4> 
as I said in the README.md
I have revised the models.py & admin.py in order to build the Post function via Django's module.
however, it didn't work and I have no idea.
Would you show me what's gonna on??

**Comment by LeoTunero** [comment]
I have figured this out already.

**Comment by VunkLai** [comment]
Your commit ref has a wrong syntax

**Comment by LeoTunero** [comment]
i have done this in 271d0cd
